-- Level 1 -> Bsic Analysis

-- 1-Show all customers who live in Karachi.
-- 2-Display all products in the Electronics category.
-- 3-Show all orders sorted by newest order date first.
-- 4-Find the total number of orders.
-- 5-Find the average price of products



-- 1-Show all customers who live in Karachi.

SELECT *
FROM Customer
WHERE city = 'Karachi';


-- 2-Display all products in the Electronics category.

SELECT *
FROM products
WHERE category = 'Electronics';

-- 3-Show all orders sorted by newest order date first.

SELECT *
FROM orders
ORDER BY order_date DESC;

-- 4-Find the total number of orders.

SELECT COUNT(*) AS Total_Number_of_Orders
FROM Orders;

-- 5-Find the average price of products

SELECT AVG(price) AS Average_Price_product
FROM products;


-- Level 2 — Product Insights

-- 6-Find the most expensive product.

-- 7-Find the cheapest product.

-- 8-Show total number of products in each category.

-- 9-Find the total quantity of items sold.

-- 10-Show products and their prices sorted from highest to lowest.


-- 6-Find the most expensive product.

SELECT TOP 1*
FROM products
ORDER BY price DESC;

-- 7-Find the cheapest product.
SELECT TOP 1*
FROM products
ORDER BY price ASC;

-- 8-Show total number of products in each category.

SELECT 
	COUNT(*) AS Total_Number_of_products_category,
	category
FROM Products
GROUP BY category;


-- 9-Find the total quantity of items sold.

SELECT SUM(qunatity) AS total_items_Sold
FROM Orders;

-- 10-Show products and their prices sorted from highest to lowest.

SELECT *
FROM Products
ORDER BY price DESC;

-- Level 3 — JOIN 

-- 11-Show customer name and their order dates.

-- 12-Show product name and quantity ordered.

-- 13️-Show customer name, product name, and quantity purchased.

-- 14-Show customer name and product they purchased.

-- 15-Show all orders with customer city.


-- 11-Show customer name and their order dates.

SELECT 
	Customer.customer_name,
	Orders.order_date
FROM Customer
INNER JOIN Orders 
ON
Customer.customer_id = Orders.customer_id;

-- 12-Show product name and quantity ordered.

SELECT 
	Products.product_name,
	Orders.qunatity
FROM Products
INNER JOIN Orders
ON
Products.product_id = Orders.order_id;

-- 13️-Show customer name, product name, and quantity purchased.

SELECT 
	Customer.customer_name,
	Products.product_name,
	Orders.qunatity
FROM Orders
INNER JOIN Customer
ON 
Orders.customer_id = Customer.customer_id
INNER JOIN Products
ON
Orders.product_id = Products.product_id;

-- 14-Show customer name and product they purchased.
SELECT 
	Customer.customer_name,
	Products.product_name
FROM Orders
LEFT JOIN Customer
ON 
Orders.customer_id = Customer.customer_id
LEFT JOIN Products
ON
Orders.product_id = Products.product_id;


-- 15-Show all orders with customer city.

SELECT 
	Customer.city,
	Orders.qunatity
FROM Orders
LEFT JOIN Customer
ON
Orders.customer_id = Customer.customer_id;


-- Level 4 — Sales Analysis

-- 16️-Calculate total revenue generated.

-- 17️-Calculate total spending for each customer.

-- 18️-Find the top 3 customers who spent the most.

-- 19-Find the best-selling product (highest quantity sold).

-- 20️-Find revenue generated by each product.


-- 16️-Calculate total revenue generated.

SELECT 
SUM(price * qunatity) AS Total_Revenue_Generated
FROM Orders
JOIN Products
ON
Orders.product_id = Products.product_id;

-- 17️-Calculate total spending for each customer.

SELECT 
	SUM(price * qunatity) AS Total_Spending_Each_Customers,
	Customer.customer_name
FROM Orders
INNER JOIN Products
ON 
Orders.product_id = Products.product_id
INNER JOIN Customer
ON
Orders.customer_id = Customer.customer_id
GROUP BY Customer.customer_name;

-- 18️-Find the top 3 customers who spent the most.

SELECT TOP 3 
	SUM(price * qunatity)  AS Total_Spending_Each_Customers,
	Customer.customer_name
FROM Orders
INNER JOIN Products
ON 
Orders.product_id = Products.product_id
INNER JOIN Customer
ON
Orders.customer_id = Customer.customer_id
GROUP BY Customer.customer_name
ORDER BY SUM(price * qunatity) DESC;

-- 19-Find the best-selling product (highest quantity sold).

SELECT
	TOP 1
	MAX(qunatity) AS Best_Selling_product,
	Products.product_name
FROM ORDERS
JOIN Products
ON
Orders.product_id = Products.product_id
GROUP BY Products.product_name
ORDER BY MAX(qunatity) DESC;

-- 20️-Find revenue generated by each product.

SELECT 
	SUM(price * qunatity) AS Revenue_generated_by_Each_Product,
	Products.product_name
FROM Products
LEFT JOIN Orders
ON
Products.product_id = Orders.product_id
GROUP BY Products.product_name;

-- Level 5 — Business Insights

-- 21-Find revenue generated by each category.

-- 22-Find which city generated the most revenue.

-- 23-Calculate monthly sales revenue.

-- 24-Find which month had the highest sales.

-- 25-Find customers who placed more than one order.


-- 21-Find revenue generated by each category.

SELECT 
	SUM(price * qunatity) AS Revenue_Generated_By_Each_category,
	Products.category
FROM Products
JOIN Orders
ON
Products.product_id = Orders.product_id
GROUP BY Products.category;

-- 22-Find which city generated the most revenue.

SELECT TOP 1 
	SUM(price * qunatity) AS revenue_generated_by_city,
	Customer.city
FROM Orders
JOIN Products
ON 
Orders.product_id = Products.product_id
JOIN Customer
ON
Orders.customer_id = Customer.customer_id
GROUP BY Customer.city
ORDER BY SUM(price * qunatity) DESC;

-- 23-Calculate monthly sales revenue.

SELECT 
	SUM(price * qunatity) AS SALES_Revenue_By_Month,
	MONTH(Orders.order_date)
FROM Orders
JOIN Products
ON 
Orders.product_id = Products.product_id
GROUP BY MONTH(Orders.order_date);

-- 24-Find which month had the highest sales.

SELECT TOP 1
	SUM(price * qunatity) AS SALES_Revenue_By_Month,
	MONTH(Orders.order_date)
FROM Orders
JOIN Products
ON 
Orders.product_id = Products.product_id
GROUP BY MONTH(Orders.order_date)
ORDER BY SUM(price * qunatity) DESC;

-- 25-Find customers who placed more than one order.
SELECT TOP 5*
FROM Customer;

--SELECT TOP 5*
--FROM Products;

SELECT TOP 5*
FROM Orders;

SELECT 
	Customer.customer_name,
	Orders.qunatity
FROM Orders
JOIN Customer
ON
Orders.customer_id = Customer.customer_id
WHERE Orders.qunatity > 1;

